# 数据源配置
spring:
  profiles:
    include: common-dev
  redis:
    database: 1
    host: ${common.redis.host}
    port: ${common.redis.port}
    password: ${common.redis.password} # 密码（默认为空）
    timeout: 6000ms       # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  rabbitmq:
    host: ${common.rabbitmq.host}
    port: ${common.rabbitmq.port}
    username: ${common.rabbitmq.username}
    password: ${common.rabbitmq.password}
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: ${common.mysql.master.url}
          username: ${common.mysql.master.username}
          password: ${common.mysql.master.password}
        flowable:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: ${common.mysql.flowable.username}
          password: ${common.mysql.flowable.password}
          # 如果不加这个参数，建表会失败：nullCatalogMeansCurrent=true
          url: ${common.mysql.flowable.url}

flowable:
  # 关闭定时任务JOB
  async-executor-activate: false
  # 将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  database-schema-update: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: cn.datax.service.workflow.api.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_empty
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# spring security 配置
security:
  oauth2:
    client:
      access-token-uri: http://16gslave:8612/auth/oauth/token
      user-authorization-uri: http://16gslave:8612/auth/oauth/authorize
      client-id: AllData
      client-secret: 123456
      scope: all
    resource:
      loadBalanced: true
      token-info-uri: http://16gslave:8612/auth/oauth/check_token

# Swagger界面内容配置
swagger:
  enable: true
  title: API接口文档
  description: Api Documentation
  version: 1.0.0
  basePackage: cn.datax.service.workflow.controller
  termsOfServiceUrl: https://github.com/alldatacenter/alldata
  contact:
    name: AllDataDC
    url: https://github.com/alldatacenter/alldata
    email: m13602574132@163.com
